# config/chewy.yml
# separate environment configs
default: &default
  host: 'localhost:9200'

development:
  <<: &default

test:
  <<: &default
  prefix: 'test'

production:
  host: <%= ENV['BONSAI_URL'] %>
