# config/chewy.yml
# separate environment configs
test:
  host: <%= ENV['ELASTICSEARCH_DEVELOPMENT_HOST'] %>
  prefix: 'test'

development:
  host: <%= ENV['ELASTICSEARCH_DEVELOPMENT_HOST'] %>

production:
  host: <%= ENV['BONSAI_URL'] %>
