default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres.service.classroom.internal
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  port: 5432
  timeout: 5000
  username: postgres

development:
  <<: *default
  database: classroom_development

test:
  <<: *default
  database: classroom_test
