development: &default
  adapter: postgresql
  encoding: unicode
  database: classroom_development
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 1) %>
  username: postgres
  password:
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>

test:
  <<: *default
  database: classroom_test
