default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 1) %>

development:
  <<: *default
  database: classroom_development

test:
  <<: *default
  database: classroom_test
